openapi: 3.0.3
info:
  title: Swagger AvisaYa - OpenAPI 3.0
  description: API de Registros de Actos Delictivos
  contact:
    email: david.valentin@unmsm.edu.pe
  version: 1.0.11
externalDocs:
  description: Más información sobre Swagger
  url: http://swagger.io
servers:
  - url: https://avisa-ya-backend-acto-delictivo-2.vercel.app/api/
tags:
  - name: actoDelictivo
    description: Operaciones acerca del acto delictivo
  - name: usuario
    description: Operaciones acerca del usuario
paths:
  /crime/buscar/{id}:
    get:
      tags:
        - actoDelictivo
      summary: Encuentra un acto delictivo por ID
      description: Retorna el registro de un acto delictivo
      operationId: buscarCrime
      parameters:
        - name: id
          in: path
          description: ID del acto delictivo a retornar
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Crime'
            application/xml:
              schema:
                $ref: '#/components/schemas/Crime'
        '400':
          description: ID Invalido
        '404':
          description: Acto Delictivo No Encontrado
      security:
        - api_key: []
        - actoDelictivo_auth:
            - write:actosDelictivos
            - read:actosDelictivos
  /crime/todos:
    get:
      tags:
        - actoDelictivo
      summary: Lista todos los actos delictivos
      description: Retorna un listado de actos delictivos
      operationId: todosCrime
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Crime'
            application/xml:
              schema:
                $ref: '#/components/schemas/Crime'
        '400':
          description: ID Invalido
        '404':
          description: Acto Delictivo No Encontrado
      security:
        - api_key: []
        - actoDelictivo_auth:
            - write:actosDelictivos
            - read:actosDelictivos
  /crime/registro:
    post:
      tags:
        - actoDelictivo
      summary: Agrega un nuevo registros de acto delictivo
      description: Agrega un nuevo registros de acto delictivo
      operationId: registroCrime
      requestBody:
        description: Crea un nuevo registros de acto delictivo
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Crime'
          application/xml:
            schema:
              $ref: '#/components/schemas/Crime'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Crime'
        required: true
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Crime'
            application/xml:
              schema:
                $ref: '#/components/schemas/Crime'
        '405':
          description: Entrada Invalida
      security:
        - actoDelictivo_auth:
            - write:actosDelictivos
            - read:actosDelictivos
  /crime/actualizar/{id}:
    put:
      tags:
        - actoDelictivo
      summary: Actualiza un acto delictivo
      description: ''
      operationId: updateActoDelictivoWithForm
      parameters:
        - name: id
          in: path
          description: ID del acto delictivo que necesita actualizarse
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '405':
          description: Entrada invalida
      security:
        - actoDelictivo_auth:
            - write:actosDelictivos
            - read:actosDelictivos
  /crime/eliminar/{id}:
    delete:
      tags:
        - actoDelictivo
      summary: Elimina un acto delictivo
      description: Elimina un acto delictivo
      operationId: eliminarCrime
      parameters:
        - name: id
          in: path
          description: Id del acto delictivo a eliminar
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '400':
          description: Valor de acto delictivo invalido
      security:
        - actoDelictivo_auth:
            - write:actosDelictivos
            - read:actosDelictivos
  /user/registro:
    post:
      tags:
        - usuario
      summary: Crear usuario
      description: Creacion de un nuevo usuario
      operationId: registroUser
      requestBody:
        description: Crear objeto usuario
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/xml:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        default:
          description: Operación exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
  /user/auth:
    post:
      tags:
        - usuario
      summary: Autenticar usuario
      description: Autenticacion de usuario usuario
      operationId: authUser
      requestBody:
        description: Autenticar usuario
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/xml:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        default:
          description: Operación exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
  /user/buscar/{id}:
    get:
      tags:
        - usuario
      summary: Obtener usuario por ID de usuario
      description: ''
      operationId: id
      parameters:
        - name: id
          in: path
          description: 'El ID que debe obtenerse. Utilice 1 para la prueba. '
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: ID de Usuario invalido
        '404':
          description: Usuario No Encontrado
  /user/actualizar/{id}:
    put:
      tags:
        - usuario
      summary: Actualizar usuario
      description: Esto solo lo puede hacer el usuario registrado.
      operationId: actualizarUser
      parameters:
        - name: id
          in: path
          description: ID del usuario que necesita ser actualizado
          required: true
          schema:
            type: string
      requestBody:
        description: Actualizar un usuario existente
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/xml:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        default:
          description: Operación exitosa
  /user/eliminar/{id}:
    delete:
      tags:
        - usuario
      summary: Delete usuario
      description: Esto solo lo puede hacer el usuario registrado.
      operationId: eliminarUser
      parameters:
        - name: id
          in: path
          description: El ID del usuario que necesita ser eliminado
          required: true
          schema:
            type: string
      responses:
        '400':
          description: ID de Usuario Invalido
        '404':
          description: Usuario No Encontrado

components:
  schemas:
    User:
      type: object
      properties:
        entityId:
          type: string
          example: 01GMFB9TM2VHV9W4N3R2VSWYMX
        usuario:
          type: string
          example: GonFreecs11
        correo:
          type: string
          example: gonfreecs11@email.com
        contrasenia:
          type: string
          example: gr33dI$l@nd
        fechaCreacion:
          type: string
          description: Fecha de creacion de usuarios
          example: '10-12-2022'
        read:
          type: string
          example: user
      xml:
        name: user
    Crime:
      required:
        - entityId
        - titulo
        - descripcion
        - hora
        - lugar
        - evidencia
        - fecha
        - categoria
        - fechaCreacion
        - id_usuario
      type: object
      properties:
        entityId:
          type: string
          example: 01GMG4MKJ55NKHEMKMV9C5MW9C
        titulo:
          type: string
          example: Robo en combi
        descripcion:
          type: string
          example: Robo celular en combi
        hora:
          type: string
          format: time
        lugar:
          type: string
          example: Av. Venezuela
        evidencia:
          type: string
          example: 'https://cdn.www.gob.pe/uploads/document/file/3360.jpg'
        fecha:
          type: string
          format: date
        estado:
          type: string
          description: Estado del Acto Delictivo
          enum:
            - Robo
            - Corrupcion
            - Asesinato
        fechaCreacion:
          type: string
          format: date-time
        id_usuario:
          type: string
          example: 01GMFB9TM2VHV9W4N3R2VSWYMX
      xml:
        name: Crime
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      xml:
        name: '##default'
  requestBodies:
    Crime:
      description: Objeto de acto delictivo que debe agregarse
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Crime'
        application/xml:
          schema:
            $ref: '#/components/schemas/Crime'
    UserArray:
      description: Lista de objetos usuario
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/User'
  securitySchemes:
    actoDelictivo_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://actoDelictivo3.swagger.io/oauth/authorize
          scopes:
            write:actosDelictivos: Modifica los actos delictivos de la cuenta
            read:actosDelictivos: Lee los actos delictivos
    api_key:
      type: apiKey
      name: api_key
      in: header